extends Node

const ID = "id"
const DATA = "data"
const USER = "user"
const OPPONENT = "opponent"
const FIRST_PLAYER = "first_player"
const BATTLEFIELD = "battlefield"
const STARTING_TIME = "starting_time"
const SELECTED_TROOPS = "selected_troops"
const CASTEL_POSITION = "castel_position"
const X = "x"
const Y = "y"
const TROOP_TYPE = "troop_type"
const QUEUE_POS = "queue_pos"
const FROM = "from"
const TO = "to"
const SNAPSHOT = "snapshot"
const IS_PLAYER1 = "is_player1"
