extends Node

class_name GameParameters

# Battelfield Generation Parameters
const TRIPLET_SAME_CHANCE = 45
const TRIPLET_GRASS_CHANCE = 21
const TRIPLET_OTHER_CHANCE = 12
const GRASSTRIPLET_SAME_CHANCE = 45
const GRASSTRIPLET_OTHER_CHANCE = 16

const TWINS_SAME_CHANCE = 20
const TWINS_GRASS_CHANCE = 12
const TWINS_OTHER_CHANCE = 6
const GRASSTWINS_SAME_CHANCE = 23
const GRASSTWINS_OTHER_CHANCE = 8

const SAME_CHANCE = 6
const GRASS_CHANCE = 6
const OTHER_CHANCE = 4
const GRASS_SAME_CHANCE = 15
const GRASS_OTHER_CHANCE = 4

const START_GRASS_CHANCE = 40
const START_OTHER_CHANCE = 20

const BATTLEFIELD_WIDTH = 21
const BATTLEFIELD_HEIGHT = 7

const DEFAULT_CASTLE_HEIGHT = 3

# Gaming Values
const DEFAULT_CASTLE_HEALTH = 300
const DEFAULT_START_GOLD = 30
const DEFAULT_BASIC_INCOME = 15

const MESSAGE_SHOW_TIME = 2
const ROUND_TIME = 4
const QUEUE_SIZE = 3