name: "Production CI"

# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: "The-Battle"

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p export/windows
          godot -v --export "windows" ./export/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: export/windows
          
  deploy:
    name: Deploy to server
    needs:  export-windows
    runs-on: ubuntu-latest
    steps:
      - name: Install SCP
        run: 
          sudo apt install -y openssh-client
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: windows
      - name: Create SSH key
        run: 
          'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SOURCEFORGE_SSH_KEY}}
      - name: Some Stuff
        run: |
          sudo chmod 600 key
          mkdir -p ~/.ssh/
      - name: Deploy to server
        run: |
          scp -P 22 -o StrictHostKeyChecking=n -i key ./$EXPORT_NAME.exe ${{ secrets.SOURCEFORGE_USER }}@frs.sourceforge.net:/home/frs/p/the-battle/v0.1.0-alpha/$EXPORT_NAME.exe
