name: "Production CI"

# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: "The Battle"

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p export/windows
          godot -v --export "Windows Desktop" ./export/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: export/windows
          
  deploy:
      name: Deploy to website
      needs:  export-windows
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: windows
        - name: Setup Github
          run: |
            git clone https://${{ secrets.PERSONAL_TOKEN }}@github.com/knobliibrot/the_battle_website.git ./the_battle_website
            git lfs install
        - name: Copy and commit fiel
          run: |
            mv ./$EXPORT_NAME.exe the_battle_website/static/$EXPORT_NAME.exe
            cd the_battle_website
            git add static/$EXPORT_NAME.exe
            git diff-index --quiet HEAD || git commit -m "Automatic commit from project: the_battle_client"
            git push target master
        
