name: "Production CI"

# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: "The-Battle"

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p export/windows
          godot -v --export "Windows Desktop" ./export/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: export/windows
          
  deploy:
      name: Deploy to website
      needs:  export-windows
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: windows
            path: ./windows
        - name: Send to Sourceforge
          run: |
           sudo apt-get install rsync grsync
           zip -r ./$EXPORT_NAME.zip ./windows
           rsync -e ssh ./$EXPORT_NAME.zip samsnorreson8@frs.sourceforge.net:/home/frs/project/the-battle/release1
